#ifndef COMMON_NOTIFY_H
#define COMMON_NOTIFY_H

#include "bus_task.h"
#include "common.h"

typedef enum {
    SYSTEM_NOTIFY_ALL = (1 << 0),
} system_notify_t;

typedef enum {
    JOINT_NOTIFY_DELTA_ELAPSED = (1 << 0),
    JOINT_NOTIFY_PWM_PULSE = (1 << 1),
    JOINT_NOTIFY_ALL = (JOINT_NOTIFY_DELTA_ELAPSED | JOINT_NOTIFY_PWM_PULSE),
} joint_notify_t;

typedef enum {
    PACKET_NOTIFY_SLAVE_SELECT = (1 << 0),
    PACKET_NOTIFY_TRANSFER_COMPLETE = (1 << 1),
    PACKET_NOTIFY_ALL =
        (PACKET_NOTIFY_SLAVE_SELECT | PACKET_NOTIFY_TRANSFER_COMPLETE),
} packet_notify_t;

typedef enum {
    LOG_NOTIFY_START = BUS_ACTION_TRANSMIT,
    LOG_NOTIFY_STOP = BUS_NOTIFY_STOP,
    LOG_NOTIFY_TRANSMIT_DONE = BUS_NOTIFY_TRANSMIT_DONE,
    LOG_NOTIFY_ALL =
        (LOG_NOTIFY_START | LOG_NOTIFY_STOP | LOG_NOTIFY_TRANSMIT_DONE),
} log_notify_t;

typedef enum {
    WATCHDOG_NOTIFY_WATCHDOG_TIMER = (1 << 0),
    WATCHDOG_NOTIFY_JOINT_ALIVE = (1 << 1),
    WATCHDOG_NOTIFY_SYSTEM_ALIVE = (1 << 2),
    WATCHDOG_NOTIFY_PACKET_ALIVE = (1 << 3),
    WATCHDOG_NOTIFY_ALL =
        (WATCHDOG_NOTIFY_WATCHDOG_TIMER | WATCHDOG_NOTIFY_JOINT_ALIVE |
         WATCHDOG_NOTIFY_SYSTEM_ALIVE | WATCHDOG_NOTIFY_PACKET_ALIVE),
} watchdog_notify_t;

#endif // COMMON_NOTIFY_H
