#ifndef ATLAS_CORE_ATLAS_STATE_H
#define ATLAS_CORE_ATLAS_STATE_H

typedef enum {
    ATLAS_STATE_IDLE,
    ATLAS_STATE_JOG,
    ATLAS_STATE_PATH,
    ATLAS_STATE_ERROR,
} atlas_state_t;

#endif // ATLAS_CORE_ATLAS_STATE_H