include_guard(GLOBAL)

set(PROJECT_DIR ${CMAKE_SOURCE_DIR})
set(MAIN_DIR ${PROJECT_DIR}/main)
set(CMAKE_DIR ${PROJECT_DIR}/cmake)
set(COMPONENTS_DIR ${PROJECT_DIR}/components)
set(SUBMODULES_DIR ${PROJECT_DIR}/submodules)
set(CUBEMX_DIR ${PROJECT_DIR}/cubemx/cmake/stm32cubemx)

function(add_subdirectories parent_dir)
    file(GLOB CHILD_DIRS RELATIVE "${parent_dir}" "${parent_dir}/*")

    foreach(child IN LISTS CHILD_DIRS)
        set(full_path "${parent_dir}/${child}")
        if(IS_DIRECTORY "${full_path}")
            if(EXISTS "${full_path}/CMakeLists.txt")
                message(STATUS "Adding subdirectory: ${full_path}")
                add_subdirectory("${full_path}")
            endif()
        endif()
    endforeach()
endfunction(add_subdirectories)
